import { Inter } from "next/font/google";
import "../styles/main.scss"
import Provider from "@/context/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AKM Ecommerce",
  description: "Generated by AKM",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
